Resources:
    myVPC:
        Type: AWS::EC2::VPC
        Properties:
            CidrBlock: 192.168.1.0/24
            EnableDnsSupport: 'true'
            EnableDnsHostnames: 'true'
            Tags:
            - Key: stack
              Value: production
